export const AI_SDLC_PHASES_FPS = 30;
export const AI_SDLC_PHASES_WIDTH = 1920;
export const AI_SDLC_PHASES_HEIGHT = 1080;
export const AI_SDLC_PHASES_DURATION = 600;
export const AI_AGENT_THREATS_DURATION = 1200;
export const REACT_REFRESH_COMPROMISE_DURATION = 1710;
